# Generated by Django 2.2.16 on 2022-08-07 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220807_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022, 'Год выпуска не может быть больше текущего')]),
        ),
    ]
